name: soopulae_tex
description: soopulae_tex_widget
version: 0.0.14+1
homepage: https://github.com/Run10Break1/soopulae_tex

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.4.3+7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - packages/soopulae_tex/assets/index.html
    # js
    - packages/soopulae_tex/assets/js/auto-render.min.js
    - packages/soopulae_tex/assets/js/katex.min.js
    - packages/soopulae_tex/assets/js/html2canvas.min.js
    # css
    - packages/soopulae_tex/assets/css/base.css
    - packages/soopulae_tex/assets/css/katex.min.css
    # font
    - packages/soopulae_tex/assets/css/fonts/KaTeX_AMS-Regular.ttf
    - packages/soopulae_tex/assets/css/fonts/KaTeX_AMS-Regular.woff
    - packages/soopulae_tex/assets/css/fonts/KaTeX_AMS-Regular.woff2
    - packages/soopulae_tex/assets/css/fonts/KaTeX_Caligraphic-Bold.ttf
    - packages/soopulae_tex/assets/css/fonts/KaTeX_Caligraphic-Bold.woff
    - packages/soopulae_tex/assets/css/fonts/KaTeX_Caligraphic-Bold.woff2
    - packages/soopulae_tex/assets/css/fonts/KaTeX_Caligraphic-Regular.ttf
    - packages/soopulae_tex/assets/css/fonts/KaTeX_Caligraphic-Regular.woff
    - packages/soopulae_tex/assets/css/fonts/KaTeX_Caligraphic-Regular.woff2
    - packages/soopulae_tex/assets/css/fonts/KaTeX_Fraktur-Bold.ttf
    - packages/soopulae_tex/assets/css/fonts/KaTeX_Fraktur-Bold.woff
    - packages/soopulae_tex/assets/css/fonts/KaTeX_Fraktur-Bold.woff2
    - packages/soopulae_tex/assets/css/fonts/KaTeX_Fraktur-Regular.ttf
    - packages/soopulae_tex/assets/css/fonts/KaTeX_Fraktur-Regular.woff
    - packages/soopulae_tex/assets/css/fonts/KaTeX_Fraktur-Regular.woff2
    - packages/soopulae_tex/assets/css/fonts/KaTeX_Main-Bold.ttf
    - packages/soopulae_tex/assets/css/fonts/KaTeX_Main-Bold.woff
    - packages/soopulae_tex/assets/css/fonts/KaTeX_Main-Bold.woff2
    - packages/soopulae_tex/assets/css/fonts/KaTeX_Main-BoldItalic.ttf
    - packages/soopulae_tex/assets/css/fonts/KaTeX_Main-BoldItalic.woff
    - packages/soopulae_tex/assets/css/fonts/KaTeX_Main-BoldItalic.woff2
    - packages/soopulae_tex/assets/css/fonts/KaTeX_Main-Italic.ttf
    - packages/soopulae_tex/assets/css/fonts/KaTeX_Main-Italic.woff
    - packages/soopulae_tex/assets/css/fonts/KaTeX_Main-Italic.woff2
    - packages/soopulae_tex/assets/css/fonts/KaTeX_Main-Regular.ttf
    - packages/soopulae_tex/assets/css/fonts/KaTeX_Main-Regular.woff
    - packages/soopulae_tex/assets/css/fonts/KaTeX_Main-Regular.woff2
    - packages/soopulae_tex/assets/css/fonts/KaTeX_Math-BoldItalic.ttf
    - packages/soopulae_tex/assets/css/fonts/KaTeX_Math-BoldItalic.woff
    - packages/soopulae_tex/assets/css/fonts/KaTeX_Math-BoldItalic.woff2
    - packages/soopulae_tex/assets/css/fonts/KaTeX_Math-Italic.ttf
    - packages/soopulae_tex/assets/css/fonts/KaTeX_Math-Italic.woff
    - packages/soopulae_tex/assets/css/fonts/KaTeX_Math-Italic.woff2
    - packages/soopulae_tex/assets/css/fonts/KaTeX_SansSerif-Bold.ttf
    - packages/soopulae_tex/assets/css/fonts/KaTeX_SansSerif-Bold.woff
    - packages/soopulae_tex/assets/css/fonts/KaTeX_SansSerif-Bold.woff2
    - packages/soopulae_tex/assets/css/fonts/KaTeX_SansSerif-Italic.ttf
    - packages/soopulae_tex/assets/css/fonts/KaTeX_SansSerif-Italic.woff
    - packages/soopulae_tex/assets/css/fonts/KaTeX_SansSerif-Italic.woff2
    - packages/soopulae_tex/assets/css/fonts/KaTeX_SansSerif-Regular.ttf
    - packages/soopulae_tex/assets/css/fonts/KaTeX_SansSerif-Regular.woff
    - packages/soopulae_tex/assets/css/fonts/KaTeX_SansSerif-Regular.woff2
    - packages/soopulae_tex/assets/css/fonts/KaTeX_Script-Regular.ttf
    - packages/soopulae_tex/assets/css/fonts/KaTeX_Script-Regular.woff
    - packages/soopulae_tex/assets/css/fonts/KaTeX_Script-Regular.woff2
    - packages/soopulae_tex/assets/css/fonts/KaTeX_Size1-Regular.ttf
    - packages/soopulae_tex/assets/css/fonts/KaTeX_Size1-Regular.woff
    - packages/soopulae_tex/assets/css/fonts/KaTeX_Size1-Regular.woff2
    - packages/soopulae_tex/assets/css/fonts/KaTeX_Size2-Regular.ttf
    - packages/soopulae_tex/assets/css/fonts/KaTeX_Size2-Regular.woff
    - packages/soopulae_tex/assets/css/fonts/KaTeX_Size2-Regular.woff2
    - packages/soopulae_tex/assets/css/fonts/KaTeX_Size3-Regular.ttf
    - packages/soopulae_tex/assets/css/fonts/KaTeX_Size3-Regular.woff
    - packages/soopulae_tex/assets/css/fonts/KaTeX_Size3-Regular.woff2
    - packages/soopulae_tex/assets/css/fonts/KaTeX_Size4-Regular.ttf
    - packages/soopulae_tex/assets/css/fonts/KaTeX_Size4-Regular.woff
    - packages/soopulae_tex/assets/css/fonts/KaTeX_Size4-Regular.woff2
    - packages/soopulae_tex/assets/css/fonts/KaTeX_Typewriter-Regular.ttf
    - packages/soopulae_tex/assets/css/fonts/KaTeX_Typewriter-Regular.woff
    - packages/soopulae_tex/assets/css/fonts/KaTeX_Typewriter-Regular.woff2

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
